file_locations.data = "data/IndividualCampaigns/Sponsored_*.csv"
data_notes = "see AAS_DataCleaningNotes_2021 doc on work Mac"

FROM BROTHER'S 
file_locations.data = "data/all_data.csv"
file_locations.monthly_summaries = "data/monthly_summaries.csv"
file_locations.book_refs = "data/book_refs.csv"
file_locations.cleaned_data = "data/all_data_cleaned.csv"
file_locations.partitioned_book_data_pattern = "data/Sponsored_*.csv"
data_notes = "data from book reference data"
