file_locations.social_merged = "data/in/test.csv"
file_locations.google_merged = "data/in/google_merge_test.csv"
file_locations.output = "data/out/output.csv"
data_notes = "data from result of merging_social_media_ad_documents and adding_google_analytics_data"